sonar.projectKey=rhode-art
sonar.organization=jesuisunjerome
sonar.host.url=https://sonarcloud.io

# --- Opcionales (ajustar si es necesario) ---
# sonar.projectName=Rhode Art
# sonar.projectVersion=1.0

# --- Definición de Módulos ---
sonar.modules=frontend,backend

# --- Módulo Frontend ---
frontend.sonar.projectName=Rhode Art Frontend
frontend.sonar.projectBaseDir=frontend
frontend.sonar.sources=src
frontend.sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js,vite.config.js,eslint.config.js

# --- Módulo Backend ---
backend.sonar.projectName=Rhode Art Backend
backend.sonar.projectBaseDir=backend
backend.sonar.sources=src
backend.sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js
